[[language]]
name = "markdown"
roots = [ ".zk" ]
language-servers = ["markdown-oxide", "mdpls"]

[language-server.mdpls]
command = "/home/autod/.cargo/bin/mdpls"
config = { markdown.preview.auto = true }
